### ISSUE TITLE
request_time unit duration inaccurate

### ISSUE THREAD

**Issue by jheld** [thiamsantos/spandex_tesla#2]
The request time duration sent to DataDog is in minutes (or at least, the calculated duration itself has an incorrect resolution).

I was able to work around it by attaching my own handler, altering the time returned by tesla telemetry, and then calling into spandex_tesla handler.

something like the following works:
```
System.convert_time_unit(request_time, :native, :millisecond) * 1_000
```

**Comment by thiamsantos** [comment]
Looking at the code of spandex_ecto, maybe we should be using nanoseconds instead of milliseconds, https://github.com/spandex-project/spandex_ecto/blob/master/lib/spandex_ecto/ecto_logger.ex#L114.

@jheld But I think you could configure the unit of the used by datadog, in the datadog configuration for that metric.

**Comment by aselder** [comment]
@thiamsantos Having done other spandex stuff, we def want that to be in nanosecond.. I'll have a PR shortyl for that and the issue I filed.
